### ISSUE TITLE
graphing and energy conversion

### ISSUE THREAD

**Issue by joshua-8** [brown-SSW/brown-solar-charger#12]
Find a factor to convert watt hours to amount of co2 saved for RI / Brown's form of energy generation

**Comment by lrandall521** [comment]
1 kWh of electricity produced in Massachusetts accounts for 0.846 lbs of carbon. (0.0023 gallons of gas per hour for a laptop)
https://www.bostonsolar.us/solar-blog-resource-center/blog/how-much-co2-do-solar-panels-save/

A laptop that is on for eight hours a day uses between 150 and 300 kWh and emits between 44 and 88 kg of CO2 per year (20g CO2 per hour on average)
https://www.energuide.be/en/questions-answers/how-much-power-does-a-computer-use-and-how-much-co2-does-that-represent/54/

**Comment by lrandall521** [comment]
![integration graphs](https://user-images.githubusercontent.com/68586187/108633202-075a8080-7441-11eb-805b-f15f70f0c37a.png)

**Comment by lrandall521** [comment]
In terms of raw energy conversion (not hourly use):
1 lbs of carbon dioxide = 1.087 kWh (https://www.eia.gov/tools/faqs/faq.php?id=74&t=11)
1 gallon gas = 33.7 kWh (https://en.wikipedia.org/wiki/Gasoline_gallon_equivalent)

**Comment by lrandall521** [comment]
Made a bunch of plots: https://docs.google.com/spreadsheets/d/1UoQ_441te4A9Lstv__UHW8SKH3CZwFIRyuwbllHcdvE/edit#gid=0
